<?php

declare(strict_types=1);

return [
    [
        'namespace' => 'qs/v1',
        'route' => '/health',
        'methods' => 'GET',
        'controller' => \QS\Interfaces\Rest\SystemController::class,
        'action' => 'health',
        'permission_callback' => '__return_true',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/version',
        'methods' => 'GET',
        'controller' => \QS\Interfaces\Rest\SystemController::class,
        'action' => 'version',
        'permission_callback' => '__return_true',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/setup',
        'methods' => 'POST',
        'controller' => \QS\Modules\Setup\Interfaces\Rest\SetupController::class,
        'action' => 'setup',
        'permission_callback' => 'canManageSetup',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/staff',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'index',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/staff/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'show',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/staff/(?P<id>\d+)/availability',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'availability',
        'permission_callback' => 'canViewAvailability',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/muas',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'muas',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/muas/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'mua',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/muas/(?P<id>\d+)/agenda',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\MuaAgendaController::class,
        'action' => 'show',
        'permission_callback' => 'canViewAgenda',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bookings',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\ReservationsController::class,
        'action' => 'index',
        'permission_callback' => 'canViewBookings',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bookings/today',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\ReservationsController::class,
        'action' => 'today',
        'permission_callback' => 'canViewBookings',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bookings/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\ReservationsController::class,
        'action' => 'show',
        'permission_callback' => 'canViewBookings',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/services',
        'methods' => 'GET',
        'controller' => \QS\Modules\ServicesCatalog\Interfaces\Rest\ServicesController::class,
        'action' => 'index',
        'permission_callback' => 'canViewServices',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/services/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\ServicesCatalog\Interfaces\Rest\ServicesController::class,
        'action' => 'show',
        'permission_callback' => 'canViewServices',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bitacoras',
        'methods' => 'GET',
        'controller' => \QS\Modules\Bitacora\Interfaces\Rest\BitacoraController::class,
        'action' => 'index',
        'permission_callback' => 'canViewBitacoras',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bitacoras',
        'methods' => 'POST',
        'controller' => \QS\Modules\Bitacora\Interfaces\Rest\BitacoraController::class,
        'action' => 'store',
        'permission_callback' => 'canManageBitacoras',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bitacoras/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Bitacora\Interfaces\Rest\BitacoraController::class,
        'action' => 'show',
        'permission_callback' => 'canViewBitacoras',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bitacoras/(?P<id>\d+)',
        'methods' => 'PUT',
        'controller' => \QS\Modules\Bitacora\Interfaces\Rest\BitacoraController::class,
        'action' => 'update',
        'permission_callback' => 'canManageBitacoras',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bitacoras/(?P<id>\d+)/summary',
        'methods' => 'GET',
        'controller' => \QS\Modules\Bitacora\Interfaces\Rest\BitacoraController::class,
        'action' => 'summary',
        'permission_callback' => 'canViewBitacoras',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bitacoras/(?P<id>\d+)/notes',
        'methods' => 'POST',
        'controller' => \QS\Modules\Bitacora\Interfaces\Rest\BitacoraController::class,
        'action' => 'addNote',
        'permission_callback' => 'canManageBitacoras',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/finance/monthly-summary',
        'methods' => 'GET',
        'controller' => \QS\Modules\Finance\Interfaces\Rest\FinanceController::class,
        'action' => 'monthlySummary',
        'permission_callback' => 'canViewFinance',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/finance/service-margin',
        'methods' => 'GET',
        'controller' => \QS\Modules\Finance\Interfaces\Rest\FinanceController::class,
        'action' => 'serviceMargin',
        'permission_callback' => 'canViewFinance',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/finance/payments',
        'methods' => 'GET',
        'controller' => \QS\Modules\Finance\Interfaces\Rest\FinanceController::class,
        'action' => 'payments',
        'permission_callback' => 'canViewFinance',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/finance/payments',
        'methods' => 'POST',
        'controller' => \QS\Modules\Finance\Interfaces\Rest\FinanceController::class,
        'action' => 'registerPayment',
        'permission_callback' => 'canManageFinance',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/finance/expenses',
        'methods' => 'GET',
        'controller' => \QS\Modules\Finance\Interfaces\Rest\FinanceController::class,
        'action' => 'expenses',
        'permission_callback' => 'canViewFinance',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/agents/status',
        'methods' => 'GET',
        'controller' => \QS\Modules\Setup\Interfaces\Rest\SetupController::class,
        'action' => 'agentsStatus',
        'permission_callback' => 'canViewAgentsStatus',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/agents/chat',
        'methods' => 'POST',
        'controller' => \QS\Modules\Agents\Interfaces\Rest\ChatbotController::class,
        'action' => 'chat',
        'permission_callback' => '__return_true', // Abierto por ahora para pruebas
    ],
];
