<?php

declare(strict_types=1);

return [
    [
        'namespace' => 'qs/v1',
        'route' => '/health',
        'methods' => 'GET',
        'controller' => \QS\Interfaces\Rest\SystemController::class,
        'action' => 'health',
        'permission_callback' => '__return_true',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/version',
        'methods' => 'GET',
        'controller' => \QS\Interfaces\Rest\SystemController::class,
        'action' => 'version',
        'permission_callback' => '__return_true',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/staff',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'index',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/staff/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'show',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/staff/(?P<id>\d+)/availability',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'availability',
        'permission_callback' => 'canViewAvailability',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/muas',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'muas',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/muas/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Team\Interfaces\Rest\StaffController::class,
        'action' => 'mua',
        'permission_callback' => 'canViewStaff',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/muas/(?P<id>\d+)/agenda',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\MuaAgendaController::class,
        'action' => 'show',
        'permission_callback' => 'canViewAgenda',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bookings',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\ReservationsController::class,
        'action' => 'index',
        'permission_callback' => 'canViewBookings',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bookings/today',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\ReservationsController::class,
        'action' => 'today',
        'permission_callback' => 'canViewBookings',
    ],
    [
        'namespace' => 'qs/v1',
        'route' => '/bookings/(?P<id>\d+)',
        'methods' => 'GET',
        'controller' => \QS\Modules\Booking\Interfaces\Rest\ReservationsController::class,
        'action' => 'show',
        'permission_callback' => 'canViewBookings',
    ],
];
