ALTER TABLE qs_sync_runs
ADD COLUMN IF NOT EXISTS created_at TIMESTAMP DEFAULT now() NOT NULL,
ADD COLUMN IF NOT EXISTS heartbeat_at TIMESTAMP,
ADD COLUMN IF NOT EXISTS worker_id VARCHAR(100),
ADD COLUMN IF NOT EXISTS attempt_count INT DEFAULT 0 NOT NULL;
